[tools]
elixir = "1.18.3-otp-27"
erlang = "27.3.3"
node = "22.18.0"
bun = "latest"
go = "latest"
direnv = "latest"
fzf = "latest"
pnpm = "latest"
yarn = "latest"
rust = "latest"
zig = "latest"
eza = "latest"
opencode = "latest"
aws = { version = "latest", symlink_bins = "true" }
kubectl = "latest"
gh = "latest"
starship = "latest"
